-- 1. DROP EVERYTHING (Start fresh)
DROP TABLE IF EXISTS attendance_records;
DROP TABLE IF EXISTS files;
DROP TABLE IF EXISTS users;
-- 2. CREATE USERS TABLE
CREATE TABLE users (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    username TEXT UNIQUE NOT NULL,
    password TEXT NOT NULL,
    role TEXT NOT NULL CHECK(role IN ('admin', 'student')),
    branch TEXT,
    email TEXT,
    created_at TIMESTAMPTZ DEFAULT CURRENT_TIMESTAMP
);
-- 3. DISABLE RLS (Very important - this allows the app to talk to the DB)
ALTER TABLE users DISABLE ROW LEVEL SECURITY;
-- 4. CREATE FILES TABLE
CREATE TABLE files (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    filename TEXT NOT NULL,
    original_name TEXT NOT NULL,
    branch TEXT NOT NULL,
    company_name TEXT NOT NULL DEFAULT 'Unknown Company',
    uploaded_by BIGINT REFERENCES users(id),
    upload_date TIMESTAMPTZ DEFAULT CURRENT_TIMESTAMP,
    is_completed BOOLEAN DEFAULT false,
    student_login_id TEXT
);
ALTER TABLE files DISABLE ROW LEVEL SECURITY;
-- 5. CREATE ATTENDANCE RECORDS TABLE
CREATE TABLE attendance_records (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    file_id BIGINT REFERENCES files(id) ON DELETE CASCADE,
    student_id BIGINT REFERENCES users(id),
    student_name TEXT NOT NULL,
    student_roll TEXT NOT NULL,
    student_branch TEXT NOT NULL,
    student_gender TEXT,
    status TEXT NOT NULL CHECK(status IN ('present', 'absent')),
    marked_at TIMESTAMPTZ DEFAULT CURRENT_TIMESTAMP
);
ALTER TABLE attendance_records DISABLE ROW LEVEL SECURITY;
-- 6. INSERT DEFAULT USERS
-- Password 'admin123'
INSERT INTO users (username, password, role, email)
VALUES (
        'admin',
        '$2b$10$uUGR1nDCTKzgnDPpcAftqOv2xUJdpCev1lPYMU0GYL4Tz/QG3Dh8y',
        'admin',
        'admin@example.com'
    );
-- Password 'student123'
INSERT INTO users (username, password, role, branch, email)
VALUES -- CSE
    (
        'CSE_MALE_2K26',
        '$2b$10$dU3Ayq7ws3vquHCX3lJUF.3tma.PPhUPYqNm7iMmbpRGHGunndDs6',
        'student',
        'CSE',
        'cse_male@example.com'
    ),
    (
        'CSE_FEMALE_2K26',
        '$2b$10$dU3Ayq7ws3vquHCX3lJUF.3tma.PPhUPYqNm7iMmbpRGHGunndDs6',
        'student',
        'CSE',
        'cse_female@example.com'
    ),
    -- AIML
    (
        'AIML_MALE_2K26',
        '$2b$10$dU3Ayq7ws3vquHCX3lJUF.3tma.PPhUPYqNm7iMmbpRGHGunndDs6',
        'student',
        'AIML',
        'aiml_male@example.com'
    ),
    (
        'AIML_FEMALE_2K26',
        '$2b$10$dU3Ayq7ws3vquHCX3lJUF.3tma.PPhUPYqNm7iMmbpRGHGunndDs6',
        'student',
        'AIML',
        'aiml_female@example.com'
    ),
    -- CSD
    (
        'CSD_MALE_2K26',
        '$2b$10$dU3Ayq7ws3vquHCX3lJUF.3tma.PPhUPYqNm7iMmbpRGHGunndDs6',
        'student',
        'CSD',
        'csd_male@example.com'
    ),
    (
        'CSD_FEMALE_2K26',
        '$2b$10$dU3Ayq7ws3vquHCX3lJUF.3tma.PPhUPYqNm7iMmbpRGHGunndDs6',
        'student',
        'CSD',
        'csd_female@example.com'
    ),
    -- ECE
    (
        'ECE_MALE_2K26',
        '$2b$10$dU3Ayq7ws3vquHCX3lJUF.3tma.PPhUPYqNm7iMmbpRGHGunndDs6',
        'student',
        'ECE',
        'ece_male@example.com'
    ),
    (
        'ECE_FEMALE_2K26',
        '$2b$10$dU3Ayq7ws3vquHCX3lJUF.3tma.PPhUPYqNm7iMmbpRGHGunndDs6',
        'student',
        'ECE',
        'ece_female@example.com'
    ),
    -- MCA
    (
        'MCA_MALE_2K26',
        '$2b$10$dU3Ayq7ws3vquHCX3lJUF.3tma.PPhUPYqNm7iMmbpRGHGunndDs6',
        'student',
        'MCA',
        'mca_male@example.com'
    ),
    (
        'MCA_FEMALE_2K26',
        '$2b$10$dU3Ayq7ws3vquHCX3lJUF.3tma.PPhUPYqNm7iMmbpRGHGunndDs6',
        'student',
        'MCA',
        'mca_female@example.com'
    );